### ISSUE TITLE
Slider (and PercentageBar) throw exception 

### ISSUE THREAD

**Issue by UgoFosforo** [stefvanschie/IF#105]
Initialize Slider (or PercentageBar) object throw exception `Length and height of pane must be greater than zero`

https://github.com/stefvanschie/IF/blob/e46e2115556455afa165be0900042df6d8bed1a5/IF/src/main/java/com/github/stefvanschie/inventoryframework/pane/component/util/VariableBar.java#L52

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in version 0.9.5.
