### ISSUE TITLE
Version not support - Mc Server Version 1.20.4

### ISSUE THREAD

**Issue by Tiri2** [stefvanschie/IF#1060]
i called `new AnvilGui(TextHolder)` but got in game this Error:
![image](https://github.com/stefvanschie/IF/assets/96706586/9ff239aa-205a-41a8-9fe6-5eba4220145e)

I dig more into the source code, and found out that the class `com.github.stefvanschie.inventoryframework.util.version.Version.java` not contains any 1.20 version. Is that right?

-----------

And the Version 1.20.5 is coming soon to paper. Will there be a update on IF? 

Ty

**Comment by stefvanschie** [comment]
I apparently overlooked this issue, sorry about that. 1.20.5 support was added in version 0.10.14.
