### ISSUE TITLE
GUI Closing when opened from another GUI

### ISSUE THREAD

**Issue by InamineDev** [stefvanschie/IF#109]
I have a menu that has sub menus.
Getting into the main menu, or any other menu, from command, works fine, and the buttons in those menus that do actions, work fine, but when I try to get to a new menu I have an issue where I have the new menu pop open for a moment and then closes.
I had it working fine and then updated to 0.8.0 and it started to have this issue. I have now updated to 0.9.5 and the issue persists.

**Comment by stefvanschie** [comment]
Could you show the code you're using to do this? I've tested this locally, but it seems to work there.

**Comment by InamineDev** [comment]
I've just tested it again. I must've had an issue with my build or something. I tested it over a few hours. Did a fresh load of my plugin and it's working again. Sorry to waste your time. Love your library!

**Comment by stefvanschie** [comment]
No problem, glad it's working now.
