### ISSUE TITLE
Getting Slider and ToggleButton Values

### ISSUE THREAD

**Issue by CronixZero** [stefvanschie/IF#110]
I searched for a method to get value from the Slider and the ToggleButton.

The Slider has a getValue() method but if you use it in the setOnClick() method the value won't be updated. 
The ToggleButton has no method to get the value as far as I saw.

**Comment by stefvanschie** [comment]
The Slider value is indeed only updated after the clicking is fired, but that can be switched around so the new value is visible when clicking. ToggleButton indeed does not have a way to check whether it is enabled or not, so a method like `isEnabled` should be added.

**Comment by stefvanschie** [comment]
Thank you, this will be added/changed in the next version.
