### ISSUE TITLE
NullPointerException thrown

### ISSUE THREAD

**Issue by CronixZero** [stefvanschie/IF#112]
If you use a PaginatedPane and then use the `#.populateWithGuiItems()` method the gui will throw a NullPointer when you click at a slot with nothing inside it.

https://prnt.sc/13a7877

**Comment by stefvanschie** [comment]
Could you share the code you used when this issue occurred? Testing this myself and I am not getting any errors when clicking on an empty slot in the gui after using `populateWithGuiItems`.

**Comment by stefvanschie** [comment]
Providing an empty list does indeed give this error, I'll make a bug fix to address this.

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.9.7.
