### ISSUE TITLE
Custom GUI size

### ISSUE THREAD

**Issue by Casper24162** [stefvanschie/IF#113]
Hello everyone,
I wanted to ask if it is possible to create inventories with there own custom sizes. Is this possible?

Thank you!
- Casper 😄

**Comment by stefvanschie** [comment]
A chest gui can have different sizes, allowing you to specify between one and six rows for your gui. The other gui types have a fixed size and those cannot be changed.

**Comment by Casper24162** [comment]
Can I specify the width of the GUI?

**Comment by stefvanschie** [comment]
No, Minecraft does not allow you to change the width of a gui and therefore IF doesn't allow this either.

**Comment by Casper24162** [comment]
Ok, thank you! 👍
