### ISSUE TITLE
Is it possible to create inventory by providing a mask?

### ISSUE THREAD

**Issue by NeumimTo** [stefvanschie/IF#115]
Is it possible to create an inventory by using a mask, similar to how spigot handles custom recipes. 

ie a mask 

11111111
111X1111
11111111

then somehow bind 1 to air and X to dirt would create an inventory with 
 rows and dirt in its middle  slot.

**Comment by stefvanschie** [comment]
Not directly, but `OutlinePane` does support masks. In your case, you could for example do the following:
```java
OutlinePane outlinePane = new OutlinePane(0, 0, 9, 3);
outlinePane.addMask(new Mask(
    "111111111",
    "111101111",
    "111111111"
));
outlinePane.setRepeat(true);
outlinePane.addItem(new GuiItem(new ItemStack(Material.AIR)));

//add outlinePane to your gui
```
Of course, a gui by default contains only air, but you can substitute the material for any other to see the effect.

**Comment by NeumimTo** [comment]
This way the mask only tells what slots are enabled/disabled.

Would it be possible to add a feature that would allow making an entire inventory from a mask?

OutlinePane outlinePane = new OutlinePane(0,0, new Mask(
    "111111111",
    "111103111",
    "111121111"
));
outlinePane.bindItem("1",new GuiItem(new ItemStack(Material.AIR)));
outlinePane.bindItem("2",new GuiItem(new ItemStack(Material.DIRT)));
outlinePane.bindItem("3",new GuiItem(new ItemStack(Material.STONE)));

**Comment by stefvanschie** [comment]
This can be added, but would probably need to be a different pane entirely, since not all of the options that are available for an `OutlinePane` make sense when using a mask as in your example.

**Comment by stefvanschie** [comment]
Thank you, this has been added in version 0.9.8.
