### ISSUE TITLE
Adventure components support

### ISSUE THREAD

**Issue by aecsocket** [stefvanschie/IF#117]
Is it possible to support Adventure's Component API in this? It was introduced in Paper 1.16.5, so there may be compatibility issues e.g. with Spigot or older versions of Paper, however I'm wondering if this is still possible to implement somehow, considering most/all other Paper API now uses components.

So far I can see that the NamedGui still uses Strings instead of Components for its title, however I'm unsure of any other places where components should be used.

**Comment by stefvanschie** [comment]
This is definitely something that would be nice, but I can't think of an easy way to integrate this currently, without breaking compatibility with CraftBukkit/Spigot (as well as earlier versions of Paper), while also having the option to make your plugin work on all platforms (CraftBukkit, Spigot, Paper, and other forks).

I think the best idea is to introduce two platforms, one for CraftBukkit and all its forks and one for Paper (and all its forks). CraftBukkit uses plain strings, while Paper can use components. That way people who want to make a plugin that just works on everything can use the CraftBukkit platform with plain strings and people who want to use Components can use the Paper platform, but at the cost of not supporting CraftBukkit and Spigot.

This is kind of a large change, but there's already been some stuff in the works on supporting other platforms, so I think this is best added along those changes.

**Comment by stefvanschie** [comment]
This will be added in version 0.10.0.
