### ISSUE TITLE
If the IF classes are loaded by other than bukkit `s default classloader exception is thrown

### ISSUE THREAD

**Issue by NeumimTo** [stefvanschie/IF#121]
in the Gui class theres code

```
 public Gui() {
        if (!hasRegisteredListeners) {
            Bukkit.getPluginManager().registerEvents(new GuiListener(),
                    JavaPlugin.getProvidingPlugin(getClass()));

            hasRegisteredListeners = true;
        }
    }
```

It does pretty much what title says, would it be possible to add overloaded constructor 

public Gui(JavaPlugin plugin) { ...

**Comment by stefvanschie** [comment]
Yes, this can be added. I'm labeling this as an enhancement, since the current code would stay the same and only an overload would be added.

**Comment by stefvanschie** [comment]
Thank you, this will be added in 0.10.0.
