### ISSUE TITLE
ClickEvents are not working after Show Panes on close Event

### ISSUE THREAD

**Issue by StayCake** [stefvanschie/IF#122]
MC-Version : 1.17 [Paper # 71]
Error-Logs : NONE

When I Shows Pane on Close, All Click events are not working.

- After Calls OnClose (InventoryCloseEvent)
![image](https://user-images.githubusercontent.com/36215887/124354972-cfaee100-dc49-11eb-80c5-e9e8b93539a0.png)

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.10.0.
