### ISSUE TITLE
AnvilGUI Bugs

### ISSUE THREAD

**Issue by CronixZero** [stefvanschie/IF#126]
When you get any ItemComponent and then use `#.setItem(GuiItem, x, y)` the item will not show up in the AnvilGUI
The Title of the AnvilGUI won't show up. It instead shows "Repair & Name"
When you input text into the AnvilGUI the ResultItem will just disappear instead of appearing with the input name

https://prnt.sc/1pxupsm

**Comment by stefvanschie** [comment]
`InventoryComponent#setItem(GuiItem, int, int)` is not meant to be used by users to place items into an inventory component. Doing this will simply override the item when the gui is rendered next time, which is probably what you're experiencing. Instead, you should create a pane, add the item to the pane and then add the pane to the inventory component.

**Comment by CronixZero** [comment]
> `InventoryComponent#setItem(GuiItem, int, int)` is not meant to be used by users to place items into an inventory component. Doing this will simply override the item when the gui is rendered next time, which is probably what you're experiencing. Instead, you should create a pane, add the item to the pane and then add the pane to the inventory component.

Oh, but how about the other things?

**Comment by CronixZero** [comment]
My bad, I tested it with the 1.8 in the beginning, sorry.

With the 1.16 it shows the title correctly but my problem with the result item is, that the item doesn't show up. I'd like the user to see the item while typing the text. If it's a feature I'm sorry for wasting your time 

https://user-images.githubusercontent.com/47929140/130130086-617b1d11-af36-416e-9344-5fb975e46f75.mp4

**Comment by stefvanschie** [comment]
This is intended, the last slot displays the item that has been programmatically set, so not the item that Vanilla would normally display. If you want it to show up as you type, you would need to program that yourself.

**Comment by CronixZero** [comment]
Okay, thank you for helping me!
