### ISSUE TITLE
XML and priorities

### ISSUE THREAD

**Issue by CDFN** [stefvanschie/IF#165]
Hey, recently I spotted small but kinda annoying bug. You have to specify priority of e.g. `outlineapge` uppercase. Otherwise you're getting error that there's no such enum (and that's a fact since enums are all uppercase in `Pane.Priority`).

**Comment by DavidTheExplorer** [comment]
Sorry to intervene, but if I understood your supposed issue correctly, how is it a bug? According to Java's conventions, enum instances should be uppercase named.

**Comment by CDFN** [comment]
Yes however in wiki it's lowercase so we should either have it uppercase in wiki or make lowercase working.

**Comment by stefvanschie** [comment]
Fixed in #166.
