### ISSUE TITLE
Unsupported Version Exception - Anvil Menu (1.18)

### ISSUE THREAD

**Issue by InamineDev** [stefvanschie/IF#173]
Attempting to open the anvil menu now results in an error when using 1.18. The rest seems to work fine, so far I've only noticed the anvil having a version issue when using 1.18

**Comment by DavidTheExplorer** [comment]
I'm not an IF's developer but can you provide the exact code? 
Even if you don't think it would help, a lot of the time a recreation is needed.

**Comment by InamineDev** [comment]
The library is hardcoded to not support 1.18 yet, so it just has to be added to the version file most likely

**Comment by stefvanschie** [comment]
1.18 support has been added in version 0.10.4. If you update to this version, your code should work on 1.18.
