### ISSUE TITLE
The default value for Percentage Bar is 100%

### ISSUE THREAD

**Issue by qsef1256** [stefvanschie/IF#175]
I want the percentage bar to show a Background Item instead of a Fill item with a progress of 0%.
but PercentageBar#setProgress(0) and PercentageBar#setProgress(1) have the same display.

Using PercentageBar#flipHorizontally was not the solution. If so, the progress is simply reversed.

Is this the intended behavior?

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.10.5.
