### ISSUE TITLE
Gui Initialization Exception

### ISSUE THREAD

**Issue by silverwolfg11** [stefvanschie/IF#201]
## Problem
Hello,

I was just trying out your framework when I received an exception from using `ChestGui.load()`.

[This is the exception](https://pastebin.com/9KF6HmDY) .

The relevant line (line 19) is just `ChestGui.load(new IFGui(), inputStream);`.

## Potential Cause
I think the reason I'm getting this error is because I am not shading in the framework into my jar, rather I am having the server load it by putting the dependency in the `libraries` section of my `plugin.yml`. This seems to cause `JavaPlugin.getProvidingPlugin(Gui.class)` (line 141 from the Gui class) to throw an illegal state exception because the classloader that loaded the Gui class is not a plugin classloader (for whatever reason).

## Setup Information
Framework Version: 0.10.5
Server Version: Paper 1.18.1 (build #133)
Java Version: Java 17
Framework obtained at runtime through the `libraries` section of the `plugin.yml`.

Please let me know if you need anymore info!

**Comment by stefvanschie** [comment]
I've opened an issue on Spigot's bug tracker for this: https://hub.spigotmc.org/jira/browse/SPIGOT-7012. I'm hoping for them to resolve this. If they won't, however, then unfortunately the usage of the libraries section cannot be used for this framework.

**Comment by stefvanschie** [comment]
Considering the answer given on the issue, IF will be unable to support declaring the dependency via the plugin.yml. I've updated the readme to reflect this. If this gets changed upstream in the future, this issue can be reopened and we can re-evaluate the usage of the plugin.yml. For now, I'll close this issue.
