### ISSUE TITLE
GuiItem's actions in a StaticPane are disabled when clicking the second time

### ISSUE THREAD

**Issue by vyketype** [stefvanschie/IF#204]
I only checked this in the StaticPane, I don't know for the other panes.
GuiItems don't do their action the second time they're clicked...

**Comment by stefvanschie** [comment]
I can't seem to reproduce this. Could you share a code snippet with the relevant code that causes this issue?

**Comment by vyketype** [comment]
I'm doing the following on a `GuiItem`: 
```java
item.setAction(event -> {
    // STUFF
    gui.update();
});
pane.addItem(item, x, y);
```
In the action block, I run `gui.update()` because I edit some of the items in the GUI.
This keeps happening in all instances of `StaticPane`.

**Comment by stefvanschie** [comment]
Thank you for the follow up. Unfortunately, I still can't seem to reproduce this issue, even when I modify some items in the gui and update it when clicking on an item. Which platform and version are you testing this on?

**Comment by stefvanschie** [comment]
I'll close this for now, if you're still having this issue, please let me know and I'll reopen this.
