### ISSUE TITLE
Add populateWithGuiItem method to PaginatedPane

### ISSUE THREAD

**Issue by DarkEyeDragon** [stefvanschie/IF#21]
Would it be possible to implement a method that lets us populate a paginated pane with gui items? this would allow us to populate easily with events. Otherwise we need to add panes manually and populate them manually as well since theres no way to attach events.

**Comment by DarkEyeDragon** [comment]
#22

**Comment by DarkEyeDragon** [comment]
#22 created a pull request for this

**Comment by stefvanschie** [comment]
Pull request #22 has been merged, so I'll close this.
