### ISSUE TITLE
ClickEvent not fired when clicking a ToggleButton

### ISSUE THREAD

**Issue by juanvlr** [stefvanschie/IF#210]
I'm using IF 0.10.5

Here is the code I have :

`ToggleButton tntDestructionButton = new ToggleButton(3, 2, 1, 1, GameConstants.ENABLE_EXPLOSIONS);`

    tntDestructionButton.setDisabledItem(new GuiItem(
            new ItemBuilder(Material.TNT)
                    .withName(Component.text("Activer destruction TNT"))
                    .build(),
            event -> {
                event.getWhoClicked().sendMessage(Component.text("La destruction de la tnt est désormais activée"));
                this.configuration.enableExplosions();
            }
    ));
    
    tntDestructionButton.setEnabledItem(new GuiItem(
            new ItemBuilder(Material.TNT)
                    .withName(Component.text("Désactiver destruction TNT"))
                    .build(),
            event -> {
                event.getWhoClicked().sendMessage(Component.text("La destruction de la tnt est désormais désactivée"));
                this.configuration.disableExplosions();
            }
    ));

**Comment by stefvanschie** [comment]
I can't seem to reproduce this issue. Which platform and Minecraft version are you using?

**Comment by juanvlr** [comment]
I'm using paper 1.16.5. Actions on cycle buttons don't work neither

**Comment by stefvanschie** [comment]
I can reproduce actions on cycle buttons not working, however toggle buttons seem to work correctly. In which type of gui are you placing these toggle buttons?

**Comment by stefvanschie** [comment]
The issue for the cycle button will be fixed in 0.10.6.

**Comment by stefvanschie** [comment]
Thank you, I'm able to reproduce it now. It seems like the click handler doesn't work properly if it's not placed at (0,0), so I'll look into fixing this.
