### ISSUE TITLE
Readme for gradle : "compile" doesn't exist.

### ISSUE THREAD

**Issue by MartinBriday** [stefvanschie/IF#217]
Hey, 

This code :
```
dependencies {
    compile 'com.github.stefvanschie.inventoryframework:IF:0.10.5'
    // ...
}
```
can't be used in gradle.

If you want to include the source code, you should use `implementation` instead, otherwise you can use `compileOnly`.

Cheers

**Comment by Unprotesting** [comment]
This should be `implementation` not `compile` or `compileOnly`.

**Comment by stefvanschie** [comment]
Thanks to RobotHanzo (#231) this has been fixed.
