### ISSUE TITLE
How get firstEmpty slot

### ISSUE THREAD

**Issue by Zoiter7** [stefvanschie/IF#226]
Hello, I tried getting the first empty slot of the inventroy with the method **gui.getInventory().getFirstEmpty()** but always returns 0.

I suppose is normal because the items are setted in the pane, so any solution for get the first empty slot of the inventory?

**Comment by stefvanschie** [comment]
This indeed doesn't work, since the underlying inventory is only updated upon rendering. It's not possible to get the first empty slot for a gui.

**Comment by stefvanschie** [comment]
Closing this, if you have follow-up questions, feel free to ask them and I'll reopen this.
