### ISSUE TITLE
Player's inventory has disappeared

### ISSUE THREAD

**Issue by MartinBriday** [stefvanschie/IF#229]
Hey!

Thanks a lot, that's a really wonderful work! Very convenient of using it! Amazing examples too!

I encounter an issue in my plugin : I add a few Label objects in the bottom-half of the GUI, and when the player close the inventory, the player's inventory has not been restored, but instead replaced with the heads created by the Labels.
It seems there to be a similar issue with the "Drawing" example : if you don't touch the glass panes, the inventory is restored; but if you start to play with them and draw something, the player's inventory is replaced with the glass panes.

Any idea of what's going on?

Cheers.

**Comment by stefvanschie** [comment]
Thank you for the report, this will be fixed in version 0.10.7.
