### ISSUE TITLE
Broken item equality check on 1.12

### ISSUE THREAD

**Issue by Plajer** [stefvanschie/IF#26]
Item equality comparisons on 1.12 for some items are broken.
https://github.com/stefvanschie/IF/blob/master/src/main/java/com/github/stefvanschie/inventoryframework/pane/OutlinePane.java#L213 this line will always return false when comparing broken item in the code below, tested StaticPane and OutlinePane, didn't work for both.

**Code:**
```java
        Gui brokenGui = new Gui(plugin, 2, "test");
        OutlinePane pane = new OutlinePane(9, 2);
        brokenGui.addPane(pane);
        brokenGui.setOnGlobalClick(e -> Bukkit.broadcastMessage("Global click"));

        ItemStack brokenBanner = new ItemStack(Material.BANNER);
        BannerMeta bannerMeta = (BannerMeta) brokenBanner.getItemMeta();
        bannerMeta.setBaseColor(DyeColor.ORANGE);
        bannerMeta.addPattern(new Pattern(DyeColor.LIGHT_BLUE, PatternType.CREEPER));
        brokenBanner.setItemMeta(bannerMeta);
        pane.addItem(new GuiItem(brokenBanner, e -> Bukkit.broadcastMessage("Banner click")));
        
        ItemStack workingItem = new ItemStack(Material.DIAMOND);
        ItemMeta meta = workingItem.getItemMeta();
        meta.setDisplayName("test test");
        meta.setLore(Arrays.asList("testtt"));
        workingItem.setItemMeta(meta);
        pane.addItem(new GuiItem(workingItem, e -> Bukkit.broadcastMessage("Working diamond click")));
        brokenGui.show(player);
```

**Expected behaviour:**
1. Broadcast "Global click" on GUI click
2. Broadcast "Banner click" on banner click
3. Broadcast "Working diamond click" on diamond click

**Actual behaviour:**
1. Broadcast "Global click" on GUI click
2. Broadcast "Working diamond click" on diamond click

**Affected versions:**
1.12 only, tested on 1.13 with BLACK_BANNER as an item and worked

I applied a temporary fix for this issue by removing item equality comparison and it was working, not sure if it's safe though.

**Comment by stefvanschie** [comment]
Reproduced, the issue seems to be on Spigot's end, however. The items are correctly compared by the `ItemStack#equals(ItemStack)` method, however this seems to fail in the scenario you showed.

As an example, the following code will also incorrectly state that the items are not the same.
```java
Inventory inventory = Bukkit.createInventory(null, 9);

ItemStack brokenBanner = new ItemStack(Material.BANNER);
BannerMeta bannerMeta = (BannerMeta) brokenBanner.getItemMeta();
bannerMeta.setBaseColor(DyeColor.ORANGE);
bannerMeta.addPattern(new Pattern(DyeColor.LIGHT_BLUE, PatternType.CREEPER));
brokenBanner.setItemMeta(bannerMeta);

inventory.addItem(brokenBanner);

player.openInventory(inventory);

@EventHandler
public void on(InventoryClickEvent e) {
    System.out.println(brokenBanner.equals(e.getCurrentItem()));
}
```

You could try asking Spigot to fix this, however I don't think they will, since they seem to have dropped 1.12 support.
