### ISSUE TITLE
IF is completely paralyzed if the player is on Spectator

### ISSUE THREAD

**Issue by DavidTheExplorer** [stefvanschie/IF#309]
If a player on spectator mode opens a GUI(tested only with ChestGUI), click event listeners don't run and who knows what else.

**Comment by Roomiiaan** [comment]
That's absolutely normal. The spectator mode prevents any interaction with inventories in vanilla

**Comment by NoahvdAa** [comment]
As @Roomiiaan said, this is intentional. In vanilla, the click actions are completely ignored. Craftbukkit will still call the events however, just cancelled by default. Try to see if you can uncancel them. If you can't, then this is probably not something we can make possible on IF's side.
