### ISSUE TITLE
Discussion: should all callbacks be wrapped so that exceptions are caught

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/IF#44]
I personally strongly believe that all callbacks should be wrapped in try-catch blocks so that even if these 3rd party code sections throw exceptions, the rest of the code continues as normal. This way we don't have to worry about IF code being interrupted, left in an intermediate, broken state. The plugin's name and if possible, some sort of gui identifier (eg. the associated class's simple name) should be included the error messages that the catch blocks produce.

Sometimes the best way to achieve this wrapping/boxing is to not expose a getter to the callback, but a method that calls the callback instead. This breaks all logic that relies on the getters, the real question is whether anything at all relies on it. Eg. `GuiItem#getAction()` returns a non-null value (it internally creates an empty lambda), in that case relying on the return value is very hard and probably no one does it. It might be possible in connection with nullable getters though.

List of what would be affected: (hopefully this is a complete list)
 - `GuiItem#getAction()`
 - `Pane#onClick` (protected variable)
 - `Gui#getOnClose()`
 - `Gui#getOnOutsideClick()`
 - `Gui#getOnGlobalClick()`
 - `Gui#getOnBottomClick()`
 - `Gui#getOnTopClick()`

I would be more than happy to implement and PR this, the question is whether I should. This is a place for arguments and counter-arguments.

**Comment by Trigary** [comment]
One counter-argument is that if plugins decide to throw exceptions in these callbacks, they should expect stuff to break. My response is that as long as the intermediate state these interrupts leave the IF library in are non-permanent, non-fatal (eg. they don't matter the next the click event is called), it's fine. But if that's not the case or if code ever gets added that might get badly hit by these uncaught exceptions problems arise. Catching them is a future-proof, guaranteed bug-free solution with little overhead (both code and runtime performance-wise) and you wouldn't have to worry/think about exceptions from callbacks at all in that case.

**Comment by stefvanschie** [comment]
I'm assuming you then want the listed methods to be transformed into some kind of `callX` method that automatically takes care of the exception handling? I'm fine with the changes to keep IF in a 'safe' state even if the user makes a `Consumer` throw an `Exception`, but I'm not certain if it's necessary to replace the current methods with these new ones or just keep both of them and internally always use the `callX` version. After all, if the user calls their own exception throwing `Consumer` retrieved from the `getX` methods as you listed, that is, at that point, their problem. It depends on if these current methods are actually used by someone I suppose; if no one uses them, no point in keeping them.

**Comment by Trigary** [comment]
> I'm assuming you then want the listed methods to be transformed into some kind of callX method that automatically takes care of the exception handling?

Yes.

> I'm not certain if it's necessary to replace the current methods with these new ones or just keep both of them and internally always use the callX version.

By replacing those getters, safety in the sense of exception handling would be enforced, there would be no way to make mistakes. Granted, this change helps the developers working on or looking at IF's code more than those who are just using it.

> After all, if the user calls their own exception throwing Consumer retrieved from the getX methods as you listed, that is, at that point, their problem.

Good counterargument, but as you also said:

> It depends on if these current methods are actually used by someone I suppose; if no one uses them, no point in keeping them.

Exactly. I personally don't think it would affect anyone at all, but that's just a wild guess.

**Comment by stefvanschie** [comment]
Let's keep this open for a little longer - if no one uses the current methods, they can go; if people are using them (and want to continue using those instead of the new `callX` versions) we can just keep them.

**Comment by stefvanschie** [comment]
I've gone through the dependents of this framework and from what I can find, none of them seem to be making use of the `getX` methods, so replacing them with their equivalent `callX` method should be fine.
