### ISSUE TITLE
Discussion: HumanEntityCache safeguard

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/IF#46]
Plugins can get disabled for many reasons (the topic is explored a bit in #45), but one of them is when the server stops (gracefully). In this case, plugins are disabled before players quit/close their inventories. So if the plugins don't explicitly close their GUIs in `onDisable` or some `PluginDisableEvent` listener, then problems arise. Even if I'm wrong about `/stop`, `/reload` is surely affected. (Although whether we want to support that command is another question.)

I suggest the addition of a safeguard that catches plugins neglecting the proper closure of inventories and therefore the restoration of player inventories. The best way to this would be to have a `PluginDisableEvent` listener and keep track of all plugin-to-gui connections in some sort of `Map`. To be able to properly implement this, #45 should be finished first.

I would be more than happy to implement and PR this, I am just asking for input regarding it. This is a place for discussion.

**Comment by stefvanschie** [comment]
I agree with this; the actions taken by IF in terms of inventory manipulation to get guis on the bottom half to properly work are intended to be handled by IF - the developer should just be able to use the extended functionality without much further thought.
