### ISSUE TITLE
ToggleButton and dumb Material...

### ISSUE THREAD

**Issue by sq179** [stefvanschie/IF#50]
[`ToggleButton`](https://github.com/stefvanschie/IF/blob/master/src/main/java/com/github/stefvanschie/inventoryframework/pane/component/ToggleButton.java) referring to `Material` for `GREEN_STAINED_GLASS_PANE` or `RED_STAINED_GLASS_PANE`, but fields not available on some versions or has changed to another, we need to move it to constructor or something else to prevent `NoSuchFieldException` on some versions.

**Comment by stefvanschie** [comment]
Some 1.12 backwards compatibility support has been added in the past for the basic Gui stuff, but not much else has really happened to ensure some kind of compatibility with pre-1.13 versions. I'd personally prefer sticking to latest, so we don't have to keep stuff for compatibility in mind and could also for example implement #48, but I don't know how much people use this for pre-1.13 versions and if they still want to keep 1.12 support in place. If there's really demand for 1.12 support, I don't mind keeping it, but that's something that we should look into.

**Comment by stefvanschie** [comment]
As per #48, we will be dropping support for 1.12 and 1.13. Because of this, the material values provided here will be kept like they currently are.
