### ISSUE TITLE
Calling Player#setItemOnCursor in Gui#setOnClose does not work

### ISSUE THREAD

**Issue by Jyguy** [stefvanschie/IF#512]
I am creating a GUI where players are able to rearrange the items within the GUI (and therefore able to have items in the cursor) without being able to move the items into their own inventory. One of the cases that allows items in the player's inventory that needs to be prevented is when the inventory is closed while an item is on the cursor. Normally, calling `player.setItemOnCursor(null);` in an `InventoryCloseEvent` listener solves the issue, but calling it in `Gui#setOnClose` does not work.

I have confirmed that the callback successfully runs by logging a message in the callback with the setItemOnCursor call.

Server version: `This server is running Pufferfish version git-Pufferfish-69 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19a70d2 on HEAD)`
IF version: `0.10.11`

**Comment by stefvanschie** [comment]
Thank you for the isue, this will be resolved in version 0.10.12.
