### ISSUE TITLE
PaginatedPane inside of MasonryPane does not show updates

### ISSUE THREAD

**Issue by DarkEyeDragon** [stefvanschie/IF#53]
When switching between pages in a PaginatedPane thats inside of a MasonryPane the page index is updated but the items in the GUI stay the same.

It seems that MasonryPane ignores index of the paginated pane when its already shown.
recreating the Gui and setting the paginated pane index before showing it works fine

**Comment by stefvanschie** [comment]
Like we discussed privately yesterday evening the gui needs to be updated manually to apply the change of setting a page. I've changed the documentation on the wiki for both the English and Dutch pages to hopefully make this more clear. Let me know if this is still unclear or needs improvement.
