### ISSUE TITLE
Error when using IF with 1.8

### ISSUE THREAD

**Issue by kadenscott** [stefvanschie/IF#54]
When using IF with 1.8, and someone clicks an empty slot in the GUI, this error appears: https://pastebin.com/K9VY5V74

Is this framework incompatible with 1.8? If it is, is there a previous version which has 1.8 support I can/should be using?

**Comment by stefvanschie** [comment]
This framework does indeed not support 1.8 and never had had a version that supports 1.8. Feel free to try different versions to see if they do work, but if you encounter any issues, we won't be resolving them.

**Comment by kadenscott** [comment]
I understand, thank you for the reply :^)
