### ISSUE TITLE
A Quick Question

### ISSUE THREAD

**Issue by test414EFF** [stefvanschie/IF#55]
Hello!
I'm currently working on a project where I'd like to have an item that, when clicked, displays a pane underneath. I just wanted to see if it was possible to add a pane to a GUI that someone currently has open (to specify, it would only appear for that one player, as a new GUI is created each time a player opens it)
Thanks

**Comment by stefvanschie** [comment]
You can modify the GUI in any way you like as long as you call `Gui#update` afterwards to refresh it for its viewers. So in your case, you can add that pane to the gui when a player clicks on it, then call `Gui#update` and the newly added pane will also be shown in the gui.

**Comment by test414EFF** [comment]
Awesome, thanks so much for your quick response!
