### ISSUE TITLE
AnvilGui improvements

### ISSUE THREAD

**Issue by AlbeMiglio** [stefvanschie/IF#562]
Status quo:

- AnvilGui doesn't contain methods to set the RenameText value (only get, #getRenameText)

**Comment by thegatesdev** [comment]
This is not possible currently. No packet exists to update the rename text the client sees from the server side.
At best you can modify the text that is tracked by the server, which will not be shown on the client and overridden when you type a new character. That can be done, but it's useless.

**Comment by AlbeMiglio** [comment]
https://github.com/WesJD/AnvilGUI does it (or makes some workaround, but the results are satisfying)

**Comment by thegatesdev** [comment]
> https://github.com/WesJD/AnvilGUI does it (or makes some workaround, but the results are satisfying)

Actually, fair enough.. it literally renames the item (hover text) in the first slot.

> // If an item is present in the left input slot change its hover name to the literal text.

In that case, you should be able to do this with IF already 😃
I think adding a dedicated method is out of the scope of IF, because it requires IF to manage the item itself (maybe @stefvanschie  thinks otherwise though)

**Comment by stefvanschie** [comment]
I agree with @thegatesdev for the reasons he listed. If it ever becomes possible to update the displayed text without modifying the item, then that is something that could be worth adding to IF. However, as it currently stands, I don't think this needs to be added as a specific method and can be done yourself by updating the name of the item in the first slot.
