### ISSUE TITLE
Custom Panes tutorial is outdated

### ISSUE THREAD

**Issue by Azim-D3Tm** [stefvanschie/IF#63]
https://github.com/stefvanschie/IF/wiki/Custom-Panes

Methods and function arguments dont match anymore, please take your time and update this section, thank you.

**Comment by stefvanschie** [comment]
Could you elaborate on which methods' arguments on that page are no longer correct?

**Comment by Azim-D3Tm** [comment]
In the part, where you make a click function, the item.getAction() no longer exists

**Comment by Azim-D3Tm** [comment]
and in **display()** part, there is no single word about what variable **start** is

**Comment by stefvanschie** [comment]
Thank you, I've changed the code you mentioned for both the English and Dutch pages to code that works with the latest version.

**Comment by Azim-D3Tm** [comment]
While we're at it, would be cool to have some sort of summary at the end, or a complete custom pane example in https://github.com/stefvanschie/IF/wiki/Examples

**Comment by stefvanschie** [comment]
I've added the full code from that page as an example on the Examples page for both the English and Dutch pages.
