### ISSUE TITLE
Suggestion: Ability to clone GUIs

### ISSUE THREAD

**Issue by Azim-D3Tm** [stefvanschie/IF#64]
Let's say i have some basic GUI which will have some information different for all of the players - such as a playerhead and some texts inside of it.
Right now, i need to construct a fresh new GUI from existing XML template, and then manually update it for my needs for each player issuing a command.
This means that each time someone runs a command, there happens a file read, which isnt that good is it?
What i suggest, is the ability to create a copy of an existing gui instance, allowing to store one instance of a gui, and make a copy of it for each player who i need to show it to, and then destroy it when it isnt needed anymore.

**Comment by stefvanschie** [comment]
Thank you, this has been added in version 0.6.2.

**Comment by Azim-D3Tm** [comment]
now the real question is: how do i get a specific item from the copied gui (RE: #65 )

**Comment by stefvanschie** [comment]
That's a good question. I think easiest would be to change the `GuiItem#copy` method so it also copies the UUID over. That way you can then get the list of items, iterate over them and find the one with the same UUID.

**Comment by Azim-D3Tm** [comment]
Maybe, instead, a copy method which would act simular to the `Gui#load(instance, InputStream)` , but taking an existing Gui instance as a second argument?
Something like `Gui newgui = Gui.copy(this, Constants.originalGuiInstance)`

**Comment by stefvanschie** [comment]
How would that help with finding an item? IF doesn't store any kind of references to fields or methods which may have been set in XML, so it can't set those fields again with the new item. Even if we would make it store this information, then this would only work if you are copying guis which originated from XML files and people who construct their gui manually, still won't be able to properly find items.

**Comment by Azim-D3Tm** [comment]
fair point

**Comment by Azim-D3Tm** [comment]
> That's a good question. I think easiest would be to change the `GuiItem#copy` method so it also copies the UUID over. That way you can then get the list of items, iterate over them and find the one with the same UUID.
please ping me when you do that

**Comment by stefvanschie** [comment]
@Azim-D3Tm Version 0.7.0 has now changed this so the `GuiItem#copy` method now also copies the uuid.
