### ISSUE TITLE
Suggestion: Unique identifiers for all of the UI elements

### ISSUE THREAD

**Issue by Azim-D3Tm** [stefvanschie/IF#65]
Would allow easier data retrieval or search of items inside of the gui.

**Comment by stefvanschie** [comment]
How would adding identifiers to UI elements make it easier to find an item? If you want to find an item, these already have a unique identifier attached which you can use. Alternatively, you can store said item in a field and retrieve it from there.

**Comment by Azim-D3Tm** [comment]
How do i add unique identifier to an item via xml?

**Comment by stefvanschie** [comment]
You can't set the identifier yourself, it's randomly generated. You can, however, specify a field attribute and the item will be stored in the field specified by the provided name. E.g., if you specify the attribute `field="myField"` on the item, then this item will be stored in the field by the name "myField".

**Comment by Azim-D3Tm** [comment]
oh, right. Sorry, i kinda forgot about that feature, my bad.
It picks the field from the class, where it has been loaded, right?

**Comment by stefvanschie** [comment]
It takes the field from the class specified in the `Gui.load` call (first parameter). The field must be public.

**Comment by Azim-D3Tm** [comment]
tyvm
