### ISSUE TITLE
Anvil GUI not working in MC 1.20.1 on v0.10.12

### ISSUE THREAD

**Issue by Kihsomray** [stefvanschie/IF#653]
I've updated the library and had multiple people reporting issues with 1.20.1 (anvil) UI not working.

I’m not that good with NMS, so you’ll probably get something out of this: https://pastebin.com/d33jmU7n

**Comment by wordandahalf** [comment]
It's a very simple fix, @stefvanschie just has to separate the 1.20.0 and 1.20.1 NMS implementations. I did this in my private fork and it worked.

**Comment by stefvanschie** [comment]
Thank you for the report, this will be fixed in 0.10.14.
