### ISSUE TITLE
How to prevent players from leaving their items in the gui's slots?

### ISSUE THREAD

**Issue by Azim-D3Tm** [stefvanschie/IF#66]
Right now players can put their stuff into the GUI inventory and it will be lost after the GUI is closed, any tips on how to avoid that?

**Comment by stefvanschie** [comment]
You can make it so they can't pickup any items anywhere (which would also prevent them from putting them into the top part) by attaching a global click handler:
```java
gui.setOnGlobalClick(event -> event.setCancelled(true));
```
Or if you still want to allow your players to move items between the bottom part, but just not place them in the top part, you can attach a top click handler:
```java
gui.setOnTopClick(event -> event.setCancelled(true));
```

Note that this also prevents any custom gui items from being picked up. If you do not want this for certain items, you can either manually override the cancellation by setting this to false again in the specific item's click handler or add checks to the global/top click handler to not cancel the event for those items.

**Comment by Azim-D3Tm** [comment]
Thank you very much
