### ISSUE TITLE
Suggestion: AnvilGUI integration

### ISSUE THREAD

**Issue by Azim** [stefvanschie/IF#74]
I am really not sure, how to do that from the technical side of things, but i think having a top half of inventory act as text input(anvil gui), and player inventory as existing inventory-based gui, would allow for much more complex interactions
https://github.com/WesJD/AnvilGUI

**Comment by Azim** [comment]
![image](https://user-images.githubusercontent.com/16478424/90665955-69011e80-e255-11ea-9b1d-27cdddc1ac69.png)

**Comment by Azim** [comment]
> Adding support for different types of guis is definitely something I want to add (not just an avil, but also for example, hoppers and droppers
any progress on that?

**Comment by stefvanschie** [comment]
I currently still need to implement some NMS to get some inventories to work and I have to test the XML; other inventory types which don't require NMS seem to work correctly so far.

**Comment by stefvanschie** [comment]
This has been added in version 0.8.0

**Comment by Azim** [comment]
> This has been added in version 0.8.0

 cant wait for update in wiki!
