### ISSUE TITLE
AnvilGUI Not Working On 1.20.2

### ISSUE THREAD

**Issue by Kyrobi** [stefvanschie/IF#742]
Server: Pufferfish 1.20.2
IF version: 0.10.12

When trying to open an anvil gui, an UnsupportedVersionException is thrown:
https://hastebin.skyra.pw/vebacusebo.pgsql

**Comment by stefvanschie** [comment]
Could you elaborate on what exactly isn't working? The gui opens for me on Minecraft 1.20.2 (IF 0.10.13), but unfortunately the link to the code you shared has expired, so I can't try your code.

**Comment by Kyrobi** [comment]
It could be that the issue got fixed when going from 0.10.12 to 0.10.13.

I'll reopen this issue if I encounter the error again
