### ISSUE TITLE
Workaround SPIGOT-4274

### ISSUE THREAD

**Issue by Jannyboy11** [stefvanschie/IF#79]
Hi there,

Since you added non-chest inventory types to your framework, I wanted to make you aware of [SPIGOT-4274](https://hub.spigotmc.org/jira/browse/SPIGOT-4274). I encountered this regression in Spigot myself when I worked on my own inventory gui framework. Paper has [patched](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0308-Restore-custom-InventoryHolder-support.patch) it, but it seems that md_5 considers it a wontfix for Spigot.

An example plugin that triggers the issue:
```java

package com.janboerman.iftest;

import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.event.Listener;
import org.bukkit.event.EventHandler;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.Material;

import com.github.stefvanschie.inventoryframework.gui.*;
import com.github.stefvanschie.inventoryframework.gui.type.*;
import com.github.stefvanschie.inventoryframework.pane.*;
import com.github.stefvanschie.inventoryframework.pane.OutlinePane;


public final class IFTest extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        // Plugin startup logic

        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent joinEvent) {
        getServer().getScheduler().runTaskLater(this, () -> {
            //create a hopper gui and the title My GUI
            HopperGui gui = new HopperGui("My GUI");
            //create a new pane occupying the entire gui
            OutlinePane pane = new OutlinePane(0, 0, 5, 1);
            ItemStack item = new ItemStack(Material.ICE);
            //create an item which will send a message when clicked
            GuiItem guiItem = new GuiItem(item, event -> event.getWhoClicked().sendMessage("You clicked on ice!"));
            //add the item to the pane
            pane.addItem(guiItem);
            //add the pane to the gui
            gui.getSlotsComponent().addPane(pane);

            //open the gui!
            gui.show(joinEvent.getPlayer());

        }, 20L);
    }
}


```

I worked around this bug in Spigot by storing the custom inventoryholders in a `WeakHashMap<Inventory, WeakReference<GuiInventoryHolder>>` in the GuiListener if the Inventory itself does not store the InventoryHolder internally (it's a WeakReference because entries won't get removed from the map automatically if a value has a strong reference to a key). See [GuiListener](https://github.com/Jannyboy11/GuiLib/blob/master/GuiLib-API/src/main/java/xyz/janboerman/guilib/api/GuiListener.java#L70).

Edit:
One other possbile way to fix it is to set the InventoryHolder in the nms class for the inventory. I didn't want to resort to NMS for my plugin, but for you this might be a viable alternative.

Groetjes,
Jan

**Comment by stefvanschie** [comment]
Thank you for the report, this has been fixed and will be in version 0.8.1.
