### ISSUE TITLE
Failed to read artifact descriptor for com.github.stefvanschie.inventoryframework:IF:jar:0.8.0

### ISSUE THREAD

**Issue by Azim** [stefvanschie/IF#80]
Whenever i try to change my dependency to use newer version
<details><summary>dependency</summary>

```
<dependency>
	<groupId>com.github.stefvanschie.inventoryframework</groupId>
	<artifactId>IF</artifactId>
	<version>0.8.0</version>
	<scope>provided</scope>
</dependency>
```

</details>

i get `Failed to read artifact descriptor for com.github.stefvanschie.inventoryframework:IF:jar:0.8.0` error from maven

**Comment by Azim** [comment]
seems to be the issue that it tries to use jitpack to download the dependency. Is there a way to force it to use maven central for that instead?

**Comment by Azim** [comment]
oh nvm it looks like a build failure
https://jitpack.io/com/github/stefvanschie/IF/v0.8.0/build.log

**Comment by stefvanschie** [comment]
Thank you for the report. There was an issue with the deployment, this should now hopefully have been fixed. Please try to build again. Note that you may need to forcibly update when building as your current local cache may be incorrect; you can do so by attaching the `-U` parameter to your Maven command (e.g., `mvn clean package -U`).

As for building manually, you seem to be missing the complete server version for 1.14.4 (i.e. the one with NMS). You can build this file locally by running BuildTools for this version; after this the error should go away.
