### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by superbiebel** [stefvanschie/IF#82]
Hi, i was just wondering if u have a discord where u can ask questions and stuff like that cuz i don't see a link to one. (not that i have any questions rn but there will certainly be some in the future.

**Comment by stefvanschie** [comment]
Currently there's no Discord guild for this framework

**Comment by superbiebel** [comment]
ngl thats a real shame, if u want i could make one. (im a senior staff member myself on the lionarch server so i could say im pretty trustable). btw geweldige lib dat je daar hebt gemaakt.

**Comment by Azim** [comment]
Relatable, i really think this framework needs a proper place to discuss and ask stuff - with discord being so popular and convenient, i was surprised to find this framework doesnt have a guild there.

**Comment by stefvanschie** [comment]
I've created a Discord guild which you can find here: https://discord.gg/RXmy4HdR4x.
