### ISSUE TITLE
GuiItem click events seemingly stopped firing after updating

### ISSUE THREAD

**Issue by aleksilassila** [stefvanschie/IF#87]
After updating to 8.0.0, all my click events stopped working, I was unable to make them fire at all. Copied the first navigation example from the wiki and seems like the issue was still present, so it shouldn't be because of my code. So the gui opens up just fine, but no click actions fire and no errors show up.

So to reproduce, just create the navigator example from wiki and add for example logs in click events, I didn't manage to get them firing. I was using ChestGui and 1.16.2.

**Comment by aleksilassila** [comment]
After intensive debugging I have come into the conclusion that it has something to do with panes. The following code fires the event:
`            ChestGui gui = new ChestGui(3, "ChestGui");
            gui.setOnGlobalClick(inventoryClickEvent -> inventoryClickEvent.setCancelled(true));

            StaticPane navigationPane = new StaticPane(1, 0, 5, 1);

            navigationPane.addItem(new GuiItem(new ItemStack(Material.DIRT), event -> System.out.println("FIRED")), 0, 0);
            gui.addPane(navigationPane);
            gui.show(player);`

But the following code does not:
`            ChestGui gui = new ChestGui(3, "ChestGui");
            gui.setOnGlobalClick(inventoryClickEvent -> inventoryClickEvent.setCancelled(true));

            StaticPane navigationPane = new StaticPane(1, 1, 5, 1); // This line changed

            navigationPane.addItem(new GuiItem(new ItemStack(Material.DIRT), event -> System.out.println("FIRED")), 0, 0);
            gui.addPane(navigationPane);
            gui.show(player);`

Both guis however display just fine.

**Comment by NoneTirex** [comment]
In the 0.8.1 version I have the same problem and items don't fire any event regardless of the item's coordinates

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in version 0.9.0.
