### ISSUE TITLE
Open new gui when the other is open

### ISSUE THREAD

**Issue by NoneTirex** [stefvanschie/IF#91]
Hi, I have a problem to open new gui while another gui is already open.

This problem happens because of this feature: https://github.com/stefvanschie/IF/blob/master/IF/src/main/java/com/github/stefvanschie/inventoryframework/gui/GuiListener.java#L310-L314

To avoid the problem problem, I used below code in my plugin, but in my opinion its not good solution:
```java
        player.closeInventory();

        Bukkit.getScheduler().runTask(JavaPlugin.getProvidingPlugin(this.getClass()), () ->
        {
            Gui menu = this.getGui();
            menu.show(player);
        });
```

According to me the problem should be resolved in inventory framework because I lost long time to find solution and it hinders implementation.

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.9.1.
