### ISSUE TITLE
Pane `click` uses incorrect length attribute in coordinate calculation

### ISSUE THREAD

**Issue by met4000** [stefvanschie/IF#93]
The `click` calculation of panes such as `StaticPane` uses the incorrect length variable in the last stage of calculation.

https://github.com/stefvanschie/IF/blob/8a92fbd8b2bc3f08f9898d6f7e0d102862a06391/IF/src/main/java/com/github/stefvanschie/inventoryframework/pane/StaticPane.java#L117-L131

Lines 125 and 126 should be using `inventoryComponent.getLength()` instead of `length`.

Below is an example of the values generated by this formula on an example 9x6 inventory (the '5x3 test pane' is highlighted in blue):
![image](https://user-images.githubusercontent.com/15624876/102294711-dcf1d000-3f84-11eb-87ff-3d4b052300d3.png)
Top left are the `slot` values for each inventory slot, top middle are the `adjustedSlot` values, top right are the `x` and `y` values for the respective slot, and bottom right are the `x` and `y` values for the respective slot using `inventoryComponent.getLength()` instead of `length`.

Testing the original version in-game yields unexpected results (the behavior is correctly predicted by the top right table), and testing a version using a custompane with the different `click` calculation produces the expected behaviour.
I haven't done in-game testing of the other pane types, but as they share this code I imagine they also have this logical error.

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.9.1.
