### ISSUE TITLE
setOnClose not working in version 0.9.0

### ISSUE THREAD

**Issue by Yepadee** [stefvanschie/IF#96]
`
@Override
public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
ChestGui cg = new ChestGui(3, "test");
cg.setOnClose(e -> 
 System.out.println("TEST");
});
cg.show((HumanEntity) sender);
return true;
}
`
I was using version 0.9.0 and "TEST" was not being printed to the terminal when the gui was closed. I then switched back to version 0.8.0 and it then worked. (Tested on spigot 1.16.4)
UPDATE - Just tested with version 0.8.1 and it appears to have been broken here.

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in 0.9.1.
