### ISSUE TITLE
IllegalAccessError: no such method

### ISSUE THREAD

**Issue by Matix-Media** [stefvanschie/IF#99]
Hi,

I'm trying to use this framework but I keep getting this error:
```
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such method: net.matixmedia.mlgrush.inventoryframework.pane.MasonryPane.load(Object,Element)MasonryPane/invokeStatic
```
I've already tried version 0.8.0 and 0.9.0 but the same error reoccurs.

I've already checked the jar and decompiled it, but the library is where it should be. If you need the pom.xml dependency:
```xml
<dependency>
    <groupId>com.github.stefvanschie.inventoryframework</groupId>
    <artifactId>IF</artifactId>
    <version>0.9.0</version>
</dependency>
```
Where I create the GUI:
```java
mapSelectionGUI = new ChestGui(5, ChatColor.DARK_AQUA + "Select a map"); // Error occurses here.
OutlinePane mapsPane = new OutlinePane(0, 0, 9, 5);
mapManager.getMaps().forEach(map -> {
    ItemStack item = new ItemBuilder(Material.PAPER, 0).setName(ChatColor.AQUA + map.getName())
            .setLore(ChatColor.GRAY + "Right/Left click to select").toItemStack();

    GuiItem gItem = new GuiItem(item, event -> {
        if (votes.containsKey(map.getName())) {
            votes.put(map.getName(), votes.get(map.getName()) + 1);
        } else {
            votes.put(map.getName(), 1);
        }
        if (event.getCurrentItem() != null) {
            event.getCurrentItem().setAmount(votes.get(map.getName()));
        }
        event.getWhoClicked().sendMessage(Main.getPrefix() + "You voted for " + ChatColor.GREEN +
                map.getName() + ChatColor.GRAY + "!");
    });
    mapsPane.addItem(gItem);
});
mapSelectionGUI.addPane(mapsPane);
```

I hope you can help me out!

**Comment by Trigary** [comment]
Are you on linux or do you have access to linux commands (eg. through git bash or WSL)? Execute the following in your plugins directory: (Hopefully it's correct, I don't have much experience with this.)
```
find . -name '*.jar' -exec jar tf {} \; | grep 'net.matixmedia.mlgrush.inventoryframework.pane.MasonryPane'
```
Basically, we want to know whether multiple JARs define the `MasonryPane`.

Also, are you running Paper or Spigot or something custom? If I remember correctly, Paper changed how plugin class loading works: if multiple plugins define the same class, each plugin will try to use the "local" definition, so the one they contain themselves. (Please don't take my word for this.) So this can also make this issue more interesting.

**Comment by Matix-Media** [comment]
So, I use paper 1.8.8 as my server jar.

There should be no other plugin using IF. The only other plugins installed are: WorldEdit, MultiVerse-Core, VoidGenerate (for multiverse-core)

**Comment by stefvanschie** [comment]
While I'm not getting the exact same error as you, you might want to know that IF doesn't support 1.8.8 and will not work on this version. To be more specific, even if the error you're getting didn't occur, you'll run into errors further down when creating a `GuiItem` because of API that was only added in 1.14 and does not exist on 1.8.8.

**Comment by Matix-Media** [comment]
ohhhh! Thank you for your help! Do you know if there is a good alternative for the 1.8?

**Comment by stefvanschie** [comment]
I know that [SmartInvs](https://github.com/MinusKube/SmartInvs) works for 1.8, so you can look into that one if you want.

**Comment by Matix-Media** [comment]
Thank you 👍 But I really like the feature set of IF. When I create a 1.14+ plugin I'm definitely using IF!

**Comment by stefvanschie** [comment]
Thank you, closing this.
